### ISSUE TITLE
Rewrite from scratch

### ISSUE THREAD

**Issue by yayayayaka** [Proggy-and-Techy-for-girls/spoilerowobot#1]
![2021-03-08-222506_526x415_scrot](https://user-images.githubusercontent.com/73759599/110385923-dc3a7880-805f-11eb-9dc1-a0c94e243451.png)

![sticker](https://user-images.githubusercontent.com/73759599/110384279-b2805200-805d-11eb-984e-1a62a9aef112.png)

**Comment by KorewaKiyo** [comment]
codecringe
